src/Web/Areas/Admin/ViewModels/Draws/EditDrawViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Core.Entities;
using Core.Utils;
using Web.Areas.Admin.ViewModels.Shared;

namespace Web.Areas.Admin.ViewModels.Draws
{
    public class EditDrawViewModel
    {
        public Guid? Guid { get; set; }
        
        [DisplayName("Extração/Concurso*")]
        [Required(ErrorMessage = "Número da extração obrigatório")]
        public int DrawNumber { get; set; }
        
        [DisplayName("Nome")]
        public string Name { get; set; }
        public IList<Ticket> Tickets { get; set; }
        
        [DisplayName("Valor da cartela*")]
        [Required(ErrorMessage = "Valor da cartela obrigatório")]
        [DisplayFormat(DataFormatString="{0:C}")]
        public decimal ValueOfTicket { get; set; }
        
        [DisplayName("Início da venda*")]
        [Required(ErrorMessage = "Início da venda obrigatório")]
        public DateTime StartDatePurchase { get; set; }
        
        [DisplayName("Fim da venda*")]
        [Required(ErrorMessage = "Fim da venda obrigatório")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy hh:mm}")]
        public DateTime EndDatePurchase { get; set; }
        public string OriginalLayoutName { get; set; }
        public string LayoutUri { get; set; }
        
        [DisplayName("Data do sorteio*")]
        [Required(ErrorMessage = "Data do sorteio obrigatório")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy hh:mm}")]
        public DateTime DrawDate { get; set; }
        public bool Accomplished { get; set; }
        
        [DisplayName("Observações")]
        public string Observations { get; set; }
        
        [DisplayName("URL do VT")]
        public string UrlCommercial { get; set; }
        
        [DisplayName("Descrição do sorteio")]
        public string DescriptionOfDraw { get; set; }
        
        [DisplayName("Descrição do resultado")]
        public string DescriptionOfResult { get; set; }
        
        [DisplayName("Ativar sorteio?")]
        public bool IsActive { get; set; }
        public int Sold { get; set; }
        public int Pending { get; set; }
        public IList<FileImport> FileImports { get; set; }
        public StatusDraw StatusDraw { get; set; }
        public int CountFileImports { get; set; }
        public DicStringStringViewModel[] Parameters { get; set; }
        
        public static EditDrawViewModel FromModel(Draw draw, int countSold, int countPending)
        {
            var vm = new EditDrawViewModel();

            if (draw != null)
            {
                vm.Guid = draw.Guid;
                vm.DrawNumber = draw.DrawNumber;
                vm.Name = draw.Name;
                vm.ValueOfTicket = draw.ValueOfTicket;
                vm.StartDatePurchase = draw.StartDatePurchase;
                vm.EndDatePurchase = draw.EndDatePurchase;
                vm.DrawDate = draw.DrawDate;
                vm.Observations = draw.Observations;
                vm.Accomplished = draw.Accomplished;
                vm.UrlCommercial = draw.UrlCommercial;
                vm.DescriptionOfDraw = draw.DescriptionOfDraw;
                vm.DescriptionOfResult = draw.DescriptionOfResult;
                vm.Sold = countSold;
                vm.Pending = countPending;
                vm.FileImports = draw.FileImports;
                vm.CountFileImports = draw.FileImports?.Count ?? 0;
                vm.IsActive = draw.IsActive;
                vm.Parameters = draw.Parameters != null
                    ? draw.Parameters.Select(d => new DicStringStringViewModel
                    {
                        Key = d.Key,
                        Value = d.Value
                    }).ToArray()
                    : new DicStringStringViewModel[] { };

                DateTime dateTimeUtc = DateTime.UtcNow;
                var brazilDatetime = dateTimeUtc.ToLocalString();
                DateTime dateTime = DateTime.Parse(brazilDatetime);
                
                if (draw.StartDatePurchase > dateTime)
                {
                    vm.StatusDraw = StatusDraw.NotStarted;
                    return vm;
                }

                if (draw.StartDatePurchase <= dateTime && !(draw.EndDatePurchase <= dateTime) && vm.IsActive)
                {
                    vm.StatusDraw = StatusDraw.InProgress;
                    return vm;
                }

                if (draw.DrawDate >= dateTime && draw.EndDatePurchase <= dateTime || draw.DrawDate <= dateTime)
                {
                    vm.StatusDraw = StatusDraw.Finished;
                    return vm;
                }
                else
                {
                    vm.StatusDraw = StatusDraw.NotStarted;
                    return vm;
                }
            }
            else
            {
                vm.ValueOfTicket = 10;
                DateTime dateTimeUtc = DateTime.UtcNow;
                var brazilDatetime = dateTimeUtc.ToLocalString();
                DateTime dateTime = DateTime.Parse(brazilDatetime);
                vm.DrawDate = dateTime;
                vm.StartDatePurchase = dateTime;
                vm.EndDatePurchase = dateTime;
            }

            return vm;
        }
    }
    
    public enum StatusDraw
    {
        NotStarted,
        InProgress,
        Finished
    }
}

src/Web/Areas/Admin/Controllers/DrawsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Threading.Tasks;
using Core.DTOs.Draws;
using Core.Entities;
using Core.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;
using System.Linq;
using System.Text;
using System.Timers;
using Core.DTOs;
using Core.DTOs.AppLogs;
using Core.DTOs.Tickets;
using Core.Entities.AppLogs;
using Core.Infrastructure;
using Core.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Primitives;
using OfficeOpenXml.FormulaParsing.Excel.Functions.DateTime;
using ServiceStack;
using Web.Areas.Admin.ViewModels.Draws;
using Queryable = Core.DTOs.Queryable;
using Type = Core.Entities.Type;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrators, Dashboards, ManageDraws")]
    public class DrawsController : Controller
    {
        private readonly IDrawsService _drawsService;
        private readonly ITicketsService _ticketsService;
        private readonly IFileManager _fileManager;
        private readonly IFileImportsService _fileImportsService;
        private readonly UserManager<AppUser> _userManager;
        private readonly IAppLogsService _appLogsService;
        private readonly IQueueItemService _queueItemService;
        private PaginatedResult<Ticket> resultTickets { get; set; }
        private PaginatedResult<Ticket> ticketsSold { get; set; }
        private PaginatedResult<Log> resultLog { get; set; }
        
        private readonly string _uriPath;
        
        public DrawsController(IDrawsService drawsService, 
            ITicketsService ticketsService, 
            IFileManager fileManager, 
            IFileImportsService fileImportsService, 
            UserManager<AppUser> userManager,
            IAppLogsService appLogsService,
            IConfiguration configuration,
            IQueueItemService queueItemService)
        {
            _drawsService = drawsService;
            _ticketsService = ticketsService;
            _fileManager = fileManager;
            _fileImportsService = fileImportsService;
            _userManager = userManager;
            _appLogsService = appLogsService;
            _uriPath = configuration["CdnPath"];
            _queueItemService = queueItemService;
        }

        public async Task<IActionResult> Index(Queryable vm)
        {
            var result = await _drawsService.ListAsync(new ListDrawsRequest
            {
                Page = vm.Page,
                PageSize = vm.PageSize,
                SearchTerm = vm.SearchTerm,
                OrderBy = vm.OrderBy,
                IsActive = vm.IsActive,
            });

            List<EditDrawViewModel> listDraw = new List<EditDrawViewModel>();
            foreach (var draw in result.Results)
            {
                var viewModel = EditDrawViewModel.FromModel(draw, 0, 0);
                listDraw.Add(viewModel);
            }
            
            ViewData["OrderBy"] = vm.OrderBy;
            ViewData["SearchTerm"] = vm.SearchTerm;
            ViewData["IsActive"] = vm.IsActive;
            ViewData["Count"] = result.Count;
            ViewData["Results"] = new StaticPagedList<EditDrawViewModel>(
                listDraw, vm.Page, vm.PageSize, result.Count);

            return View();
        }

        public async Task<IActionResult> Edit(Guid id, EditDrawViewModel vm)
        {
            switch (Request.Method)
            {
                case "GET":
                {
                    // Get existing user
                    int ticketsPending = 0;
                    var draw = await _drawsService.GetUniqueAsync(id);

                    if (draw != null)
                        ticketsPending = await _ticketsService.CountPending(draw.Guid);
                        
                    var viewModel = EditDrawViewModel.FromModel(draw, 0, ticketsPending);

                    ModelState.Clear();
                    return View(viewModel);
                }

                case "POST" when !ModelState.IsValid:
                    ViewBag.Error = "Error";
                    return View(vm);
            }

            if (vm.IsActive)
            {
                //Validações
                DateTime dateTimeUtc = DateTime.UtcNow;
                var brazilDatetime = dateTimeUtc.ToLocalString();
                DateTime dateTime = DateTime.Parse(brazilDatetime);
               
                if (vm.StartDatePurchase < dateTime)
                    ModelState.AddModelError(string.Empty, "Data de início da venda menor que a data atual.");
            
                if(vm.EndDatePurchase < dateTime)
                    ModelState.AddModelError(string.Empty, "Data fim da venda menor que a data atual.");
            
                if(vm.DrawDate < dateTime)
                    ModelState.AddModelError(string.Empty, "Data do sorteio menor que a data atual.");
            
                if (vm.StartDatePurchase > vm.EndDatePurchase)
                    ModelState.AddModelError(string.Empty, "Data de início da venda maior que a data de fim da venda.");
            
                if (vm.DrawDate < vm.EndDatePurchase)
                    ModelState.AddModelError(string.Empty, "Data do sorteio menor que a data de fim da venda.");
            
                if (vm.StartDatePurchase > vm.DrawDate)
                    ModelState.AddModelError(string.Empty, "Data de início da venda maior que a data do sorteio.");
                
                var activeDraw = await _drawsService.GetActiveAsync();
                if (activeDraw != null && activeDraw.Guid != vm.Guid)
                    ModelState.AddModelError(string.Empty, "Outro sorteio está ativo, apenas um sorteio pode está ativo.");
                
                if (vm.Pending == 0)
                    ModelState.AddModelError(string.Empty, "Nenhuma carga de cartelas incluída no sorteio, inclua as cartelas para ativá-lo.");
                
                if (vm.CountFileImports != 3)
                    ModelState.AddModelError(string.Empty, "Algum arquivo pendente no sorteio, verifique a carga de cartelas, imagem da cartela e regulamento.");
            }
            
            if (ModelState.ErrorCount > 0)
            {
                ViewBag.Error = "Error";
                return View(vm);
            }

            var userLog = await _userManager.FindByNameAsync(User.Identity.Name);
            
            var request = new SaveDrawRequest
            {
                Guid = vm.Guid,
                DrawNumber = vm.DrawNumber,
                Name = vm.Name,
                ValueOfTicket = vm.ValueOfTicket,
                StartDatePurchase = vm.StartDatePurchase,
                EndDatePurchase = vm.EndDatePurchase,
                Observations = vm.Observations,
                OriginalLayoutName = vm.OriginalLayoutName,
                LayoutUri = vm.LayoutUri,
                DrawDate = vm.DrawDate,
                Accomplished = vm.Accomplished,
                UrlCommercial = vm.UrlCommercial,
                DescriptionOfDraw = vm.DescriptionOfDraw,
                DescriptionOfResult = vm.DescriptionOfResult,
                IsActive = vm.IsActive,
                UserModification = userLog.Id,
                Parameters = vm.Parameters?
                    .Where(t => t.Key != null && t.Value != null)
                    .ToDictionary(t => t.Key, t => t.Value)
            };

            var res = await _drawsService.SaveAsync(request);

            return RedirectToAction("View", new {id = res.Guid, isSaved = true, alert = true});
        }

        public async Task<IActionResult> View(Guid id, Queryable pagination, bool isSaved = false, string message = null, bool alert = false)
        {
            if (isSaved) ViewBag.Message = message ?? "Sorteio salvo com sucesso";
            ViewBag.Alert = alert ? "Success" : "Error";

            if (pagination.ReturnToView != null && pagination.ReturnToView == "tickets")
            {
                resultTickets = await _ticketsService.ListAsync(new ListTicketsRequest
                {
                    Page = pagination.Page,
                    PageSize = pagination.PageSize,
                    SearchTerm = pagination.SearchTerm,
                    IsActive = pagination.IsActive,
                    DrawGuid = id
                });
                
                ViewData["ResultTickets"] = new StaticPagedList<Ticket>(
                    resultTickets.Results, pagination.Page, pagination.PageSize, resultTickets.Count);
            }
            else if (pagination.ReturnToView != null && pagination.ReturnToView == "historic")
            {
                resultLog = await _appLogsService.ListAsync(new ListLogsRequest
                {
                    Page = pagination.Page,
                    PageSize = pagination.PageSize,
                    userGuid = id
                });
                
                ViewData["ResultsLogs"] = new StaticPagedList<Log>(
                    resultLog.Results, pagination.Page, pagination.PageSize, resultLog.Count);    
            }
            
            ViewBag.ActiveTab = pagination.ReturnToView ?? "overview";

            if (resultLog == null)
            {
                resultLog = await _appLogsService.ListAsync(new ListLogsRequest
                {
                    Page = 1,
                    PageSize = 10,
                    userGuid = id
                });
            
                
                ViewData["ResultsLogs"] = new StaticPagedList<Log>(
                                    resultLog.Results, 1, 10, resultLog.Count);
            }

            if (resultTickets == null)
            {

src/Web/Areas/Admin/Views/Draws/Edit.cshtml
@using Microsoft.CodeAnalysis
@using Core.Utils
@model Web.Areas.Admin.ViewModels.Draws.EditDrawViewModel

@{
    const string labelClasses = "text-sm-right col-sm-3 col-form-label";
    const string inputClasses = "form-control";
    const string validationMessageClasses = "text-danger small";
}

<h3 class="mt-2 mb-4">
    @if (Model.Guid.HasValue)
    {
        ViewData["Title"] = "Editar";
        <Text>Editar sorteio</Text>
    }
    else
    {
        ViewData["Title"] = "Novo";
        <Text>Novo sorteio</Text>
    }
</h3>

<div class="card">
    <div class="card-body pt-5 px-5">
        @if (ViewBag.Message != null)
        {
            <div class="row form-group">
                <div class="col-12 ">
                    <div class="alert alert-success">
                        @ViewBag.Message
                    </div>
                </div>
            </div>
        }
        
        @if (ViewBag.Error != null)
        {
            <div class="row form-group">
                <div class="col-12 ">
                    <div class="alert alert-danger">
                        @Html.ValidationSummary()
                    </div>
                </div>
            </div>
        }

        @if (User.IsInRole("Administrators") || User.IsInRole("ManageDraws"))
        {
            using (Html.BeginForm("Edit", "Draws", FormMethod.Post))
            {
                @Html.HiddenFor(m => m.Guid)
                @Html.HiddenFor(m => m.Pending)
                @Html.HiddenFor(m => m.CountFileImports)

                <div class="row">
                    <div class="col-12">
                        <h4>Sorteio</h4>
                    </div>
                </div>

                <div class="row form-group">
                    @Html.LabelFor(m => m.DrawNumber, new {@class = labelClasses})
                    <div class="col-sm-9">
                        @Html.TextBoxFor(m => m.DrawNumber, new {@class = inputClasses})
                        @Html.ValidationMessageFor(m => m.DrawNumber, string.Empty, new {@class = validationMessageClasses})
                    </div>
                </div>

                <div class="row form-group">
                    @Html.LabelFor(m => m.Name, new {@class = labelClasses})
                    <div class="col-sm-9">
                        @Html.TextBoxFor(m => m.Name, new {@class = inputClasses})
                        @Html.ValidationMessageFor(m => m.Name, string.Empty, new {@class = validationMessageClasses})
                    </div>
                </div>

                <div class="row form-group">
                    @Html.LabelFor(m => m.ValueOfTicket, new {@class = labelClasses})
                    <div class="col-sm-9">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">R$</span>
                            @Html.TextBoxFor(m => m.ValueOfTicket, new {@class = inputClasses})
                          </div>
                        @Html.ValidationMessageFor(m => m.ValueOfTicket, string.Empty, new {@class = validationMessageClasses, id = "ValueOfTicket", type = "datetime-local"})
                    </div>
                </div>

                <div class="row form-group">
                    @Html.LabelFor(m => m.StartDatePurchase, new {@class = labelClasses})
                    <div class="col-sm-9">
                        @Html.TextBoxFor(m => m.StartDatePurchase, "{0:dd/MM/yyyy hh:mm}", new {@class = inputClasses, type = "datetime-local", id = "StartDatePurchase"})
                        @Html.ValidationMessageFor(m => m.StartDatePurchase, string.Empty, new {@class = validationMessageClasses})
                    </div>
                </div>
                
                <div class="row form-group">
                    @Html.LabelFor(m => m.EndDatePurchase, new {@class = labelClasses})
                    <div class="col-sm-9">
                        @Html.TextBoxFor(m => m.EndDatePurchase, new {@class = inputClasses, type = "datetime-local", id = "EndDatePurchase"})
                        @Html.ValidationMessageFor(m => m.EndDatePurchase, string.Empty, new {@class = validationMessageClasses})
                    </div>
                </div>
                
                <div class="row form-group">
                    @Html.LabelFor(m => m.DrawDate, new {@class = labelClasses})
                    <div class="col-sm-9">
                        @Html.TextBoxFor(m => m.DrawDate, new {@class = inputClasses, type = "datetime-local", id = "DrawDate"})
                        @Html.ValidationMessageFor(m => m.DrawDate, string.Empty, new {@class = validationMessageClasses})
                    </div>
                </div>
                
                <div class="row form-group">
                    @Html.LabelFor(m => m.UrlCommercial, new {@class = labelClasses})
                    <div class="col-sm-9">
                        @Html.TextBoxFor(m => m.UrlCommercial, new {@class = inputClasses})
                        @Html.ValidationMessageFor(m => m.UrlCommercial, string.Empty, new {@class = validationMessageClasses})
                    </div>
                </div>
                
                <div class="row form-group">
                    @Html.LabelFor(m => m.Observations, new {@class = labelClasses})
                    <div class="col-sm-9">
                        @Html.TextAreaFor(m => m.Observations, new {@class = inputClasses})
                        @Html.ValidationMessageFor(m => m.Observations, string.Empty, new {@class = validationMessageClasses})
                    </div>
                </div>
                
                @if (Model.Guid.HasValue)
                {
                    <div class="row form-group">
                        @Html.LabelFor(m => m.IsActive, new {@class = labelClasses})
                        <div class="col-sm-9">
                            @Html.CheckBoxFor(m => m.IsActive, new {style="margin-top: 20px;"})
                        </div>
                    </div>
                }
                
                @Html.EditorFor(m => m.Parameters, "Data")

                <div class="row form-group mt-5">
                    <div class="col-sm-9 offset-sm-3">
                        <button class="btn btn-primary">Salvar</button>
                    </div>
                </div>
            }
        }
        else
        {
            using (Html.BeginForm("Edit", "Draws", FormMethod.Post))
            {
                @Html.HiddenFor(m => m.Guid)
                @Html.HiddenFor(m => m.Pending)
                @Html.HiddenFor(m => m.CountFileImports)
                @Html.HiddenFor(m => m.DrawNumber)
                @Html.HiddenFor(m => m.Name)
                @Html.HiddenFor(m => m.ValueOfTicket)
                @Html.HiddenFor(m => m.StartDatePurchase)
                @Html.HiddenFor(m => m.EndDatePurchase)
                @Html.HiddenFor(m => m.DrawDate)
                @Html.HiddenFor(m => m.Observations)
                @Html.HiddenFor(m => m.IsActive)
                @Html.HiddenFor(m => m.IsActive)

                <div class="row">
                    <div class="col-12">
                        <h4>Sorteio</h4>
                    </div>
                </div>

                <div class="row form-group">
                    @Html.LabelFor(m => m.DrawNumber, new {@class = labelClasses})
                    <div class="col-sm-9">
                        @Html.TextBoxFor(m => m.DrawNumber, new {@class = inputClasses, disabled = "disabled" })
                    </div>
                </div>

                <div class="row form-group">
                    @Html.LabelFor(m => m.Name, new {@class = labelClasses})
                    <div class="col-sm-9">
                        @Html.TextBoxFor(m => m.Name, new {@class = inputClasses, disabled = "disabled" })
                    </div>
                </div>

                <div class="row form-group">
                    @Html.LabelFor(m => m.UrlCommercial, new {@class = labelClasses})
                    <div class="col-sm-9">
                        @Html.TextBoxFor(m => m.UrlCommercial, new {@class = inputClasses})
                        @Html.ValidationMessageFor(m => m.UrlCommercial, string.Empty, new {@class = validationMessageClasses})
                    </div>
                </div>
                
                <div class="row form-group mt-5">
                    <div class="col-sm-9 offset-sm-3">
                        <button class="btn btn-primary">Salvar</button>
                    </div>
                </div>
            }
        }
        
        
    </div>
</div>


@section Scripts {
    <script src="~/js/jquery.mask.js"></script>
    <script src="~/js/moment.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
              $('#ValueOfTicket').mask("#.##0,00", {reverse: true});
              
              var valueStartDatePurchase = '@Model.StartDatePurchase';
              var valueEndDatePurchase = '@Model.EndDatePurchase';
              var valueDrawDate = '@Model.DrawDate';
              
              if (valueStartDatePurchase !== '' && valueEndDatePurchase !== '' && valueDrawDate !== '')
              {
                  var dataValueStartDatePurchase = moment(valueStartDatePurchase, "DD/MM/YYYY hh:mm");
                  var dateStartDatePurchase = dataValueStartDatePurchase.format("YYYY-MM-DDTHH:mm");
                  document.getElementById('StartDatePurchase').value = dateStartDatePurchase;
                  
                  var dataValueEndDatePurchase = moment(valueEndDatePurchase, "DD/MM/YYYY hh:mm");
                  var dateEndDatePurchase = dataValueEndDatePurchase.format("YYYY-MM-DDTHH:mm");
                  document.getElementById('EndDatePurchase').value = dateEndDatePurchase;
                  
                  var dataValueDrawDate = moment(valueDrawDate, "DD/MM/YYYY hh:mm");
                  var dateDrawDate = dataValueDrawDate.format("YYYY-MM-DDTHH:mm");
                  document.getElementById('DrawDate').value = dateDrawDate;
              }
              
        });
    </script>
}