src/Web/Areas/Admin/ViewModels/AppLogs/AppLogViewModel.cs
using System;
using System.ComponentModel;
using Core.Entities;
using Core.Entities.AppLogs;
using Web.Areas.Admin.ViewModels.Users;

namespace Web.Areas.Admin.ViewModels.AppLogs
{
    public class AppLogViewModel
    {
        public Guid? Guid { get; set; }

        [DisplayName("Data Criação")]
        public DateTime CreatedAt { get; set; }

        [DisplayName("Tipo Log")]
        public string LogType { get; set; }

        [DisplayName("Usuário")]
        public UserViewModel User { get; set; }

        public static AppLogViewModel FromModel(Log log, AppUser user)
        {
            var vm = new AppLogViewModel();

            if (log != null)
            {
                vm.Guid = log.Guid;
                vm.CreatedAt = log.CreatedAt;
                vm.LogType = log.LogType.ToString();
                vm.User = UserViewModel.FromModel(user, null);
            }

            return vm;
        }
    }
}

src/Web/Areas/Admin/Controllers/AppLogsController.cs
using Core.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;
using Core.Entities.AppLogs;
using Microsoft.AspNetCore.Authorization;
using X.PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using Core.DTOs;
using Core.Utils;
using Core.DTOs.AppLogs;
using Core.Entities;
using Web.Areas.Admin.ViewModels.AppLogs;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Administrators")]
    public class AppLogsController : Controller
    {
        private readonly IAppLogsService _appLogsService;
        private readonly IUsersService _usersService;

        public AppLogsController(IAppLogsService appLogsService, IUsersService usersService)
        {
            _appLogsService = appLogsService;
            _usersService = usersService;
        }

        public async Task<IActionResult> Index(Queryable vm)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            if (!User.IsInRole("Administrators"))
                RedirectToAction("Index", "Home");

            var result = await _appLogsService.ListAsync(new ListLogsRequest
            {
                Page = vm.Page,
                PageSize = vm.PageSize,
                SearchTerm = vm.SearchTerm,
                OrderBy = vm.OrderBy,
                IsActive = vm.IsActive,
            });
            
            /*var result = await _appLogsService.ListAsync(new ListLogsRequest
            {
                Page = vm.Page,
                PageSize = vm.PageSize,
                SearchTerm = vm.SearchTerm,
                OrderBy = vm.OrderBy,
                IsActive = vm.IsActive,
            });

            ViewData["OrderBy"] = vm.OrderBy;
            ViewData["SearchTerm"] = vm.SearchTerm;
            ViewData["IsActive"] = vm.IsActive;

            ViewData["Count"] = result.Count;*/
            //ViewData["Results"] = new StaticPagedList<Log>(result.Results, vm.Page, vm.PageSize, result.Count);

            return View();
        }

        public async Task<IActionResult> View(Guid id)
        {
            var log = await _appLogsService.GetAsync(id);

            var user = log.UserGuid.HasValue
                ? await _usersService.GetAsync(log.UserGuid.Value)
                : ((AppUser, IList<string>)?) null;

            var viewModel = AppLogViewModel.FromModel(log, null);

            return View(viewModel);
        }

        public async Task<IActionResult> Export(Queryable vm)
        {
            /*var result = await _appLogsService.ListAsync(new ListLogsRequest
            {
                Page = vm.Page,
                PageSize = vm.PageSize,
                SearchTerm = vm.SearchTerm,
                OrderBy = vm.OrderBy,
                IsActive = vm.IsActive,
            });*/

            await using var memoryStream = new MemoryStream();
            //result.Results.ExportXlsx("Logs", memoryStream);

            return File(
                memoryStream.ToArray(),
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                $"logs-{DateTime.UtcNow:dd-MM-yyyy}.xlsx");
        }
    }
}

src/Web/Areas/Admin/Views/AppLogs/Index.cshtml
@using Core.Utils
@using Core.Entities.AppLogs
@using X.PagedList;
@using X.PagedList.Mvc.Core
@using X.PagedList.Mvc.Core.Common

@{
    ViewData["Title"] = "Logs";
    var logs = (IPagedList<Log>)ViewData["Results"];
}

<h3 class="mt-2 mb-4">
    Logs
</h3>

<div class="card">
    <div class="card-body py-5">

        @using (Html.BeginForm("Index", "AppLogs", FormMethod.Post))
        {
            <div class="row">
                <div class="col-12 col-md-8 mb-4 mb-md-0">
                    <input type="text" name="searchTerm" class="form-control" placeholder="Buscar..." value="@ViewData["SearchTerm"]" />
                </div>
                <div class="col-12 col-md-4 mb-4 mb-md-0">
                    <button type="submit" class="btn btn-block btn-primary">
                        <i class="fas fa-search"></i>
                        Buscar
                    </button>
                </div>
            </div>
        }

        <div class="table-responsive">
            <table class="table m-0">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Tipo Log</th>
                        <th scope="col">Data</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in logs)
                    {
                        <tr>
                            <td>
                                <button class="btn btn-sm btn-secondary copy-btn" data-clipboard-text="@item.Guid">
                                    @item.Guid.ToString().Substring(0, 5)...
                                    <i class="fas fa-copy ml-2"></i>
                                </button>
                            </td>
                            <td>
                                @item.LogType.ToString()
                            </td>
                            <td>
                                @item.CreatedAt.ToLocalString()
                            </td>
                            <td>
                                <a asp-controller="AppLogs" asp-action="View" asp-route-id="@item.Guid" class="btn btn-light btn-sm">
                                    <i class="fas fa-eye"></i>
                                    Visualizar
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        <div class="row">
            <div class="col-12 col-md-8">
                @Html.PagedListPager(
                    logs,
                    page => Url.Action("Index",
                        new
                        {
                            page,
                            SearchTerm = ViewData["SearchTerm"],
                            OrderBy = ViewData["OrderBy"],
                            IsActive = ViewData["IsActive"]
                        }),
                    new PagedListRenderOptions
                    {
                        LiElementClasses = new[] { "page-item" },
                        PageClasses = new[] { "page-link" },
                        DisplayEllipsesWhenNotShowingAllPageNumbers = false
                    }
                )
            </div>
            <div class="col-12 col-md-4">
                <a asp-controller="AppLogs" asp-action="Export" class="btn btn-block btn-sm btn-dark">
                    Exportar @ViewData["Count"] Log(s)
                </a>
            </div>
        </div>
    </div>
</div>

<div class="toast" style="position: fixed; bottom: 20px; right: 20px;">
    <div class="toast-header">
        <strong class="mr-auto">Sistema</strong>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="toast-body text-success">
        Guid copiado para área de transferência!
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            window.clipboard.on('success', function (e) {
                e.clearSelection();
                $('.toast').toast('show');
            });

            $('.toast').toast({
                delay: 5000,
            });
        });
    </script>
}

src/Web/Areas/Admin/Views/AppLogs/View.cshtml
@using Core.Utils
@model Web.Areas.Admin.ViewModels.AppLogs.AppLogViewModel

@{
    ViewData["Title"] = "Visualizar";
    const string labelClasses = "text-sm-right col-sm-3 col-form-label";
    const string inputClasses = "form-control";
}

<h3 class="mt-2 mb-4">
    <Text>Visualizar Logs</Text>
</h3>

<div class="card">
    <div class="card-body py-5">

        <div class="row">
            <h4>Log</h4>
        </div>

        <div class="row form-group">
            @Html.LabelFor(m => m.LogType, new { @class = labelClasses })
            <div class="col-sm-9">
                @Html.DisplayFor(m => m.LogType, new { @class = inputClasses})
            </div>
        </div>

        <div class="row form-group">
            @Html.LabelFor(m => m.CreatedAt, new { @class = labelClasses })
            <div class="col-sm-9">
                @Html.DisplayFor(m => m.CreatedAt, new { @class = inputClasses})
            </div>
        </div>
        <div class="row form-group">
            @Html.LabelFor(m => m.User.FirstName, new { @class = labelClasses })
            <div class="col-sm-9">
                @Html.DisplayFor(m => m.User.FirstName, new { @class = inputClasses})
            </div>
        </div>
        <div class="row form-group">
            @Html.LabelFor(m => m.User.Email, new { @class = labelClasses })
            <div class="col-sm-9">
                @Html.DisplayFor(m => m.User.Email, new { @class = inputClasses})
            </div>
        </div>
    </div>
</div>